Update ubuntu.yml

diff --git a/.github/workflows/ubuntu.yml b/.github/workflows/ubuntu.yml
--- a/.github/workflows/ubuntu.yml
+++ b/.github/workflows/ubuntu.yml
@@ -3,9 +3,9 @@ name: Guile Build & Test on Ubuntu
 on:
   # Trigger on push to main branch and pull requests
   push:
-    branches: [ $default-branch ]
+    branches: [ master ]
   pull_request:
-    branches: [ $default-branch ]
+    branches: [ master ]
   # Allow manual triggering
   workflow_dispatch:
 
@@ -54,10 +54,17 @@ jobs:
           libltdl-dev \
           libncurses5-dev \
           libreadline-dev \
-          libunistring-dev
+          libunistring-dev \
+          locales
+        sudo logale-gen en_US.UTF-8
+        sudo update-locale LANG=en_US.UTF-8
     - name: Configure
       run: |
-        export LANG=C.UTF-8 TERM=dumb VERBOSE=true DEBIAN_FRONTEND=noninteractive TZ=America/Los_Angeles
+        export LANG=C.UTF-8
+        export TERM=dumb
+        export VERBOSE=true
+        export DEBIAN_FRONTEND=noninteractive
+        export TZ=America/Los_Angeles
         export TOP="$(pwd)"
         set -e  # Exit on any error
         mkdir -p "$(pwd)/app" && \
@@ -74,7 +81,7 @@ jobs:
 
     # Step to handle the build success
     - name: Handle Build Success
-      if: steps.build.outcome == 'success'
+      if: ${{ steps.build.outcome == 'success' }}
       run: |
         # Create the success badge
         mkdir -p ./badges/${{ github.repository }}/${{ github.ref_name }}/
@@ -91,8 +98,8 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     # Step to handle the build failure case
-    - name: Handle Buile Failure
-      if: steps.build.outcome != 'success'
+    - name: Handle Build Failure
+      if: ${{ steps.build.outcome != 'success' }}
       run: |
         # Create the failure badge
         mkdir -p ./badges/${{ github.repository }}/${{ github.ref_name }}/
@@ -110,10 +117,11 @@ jobs:
 
     # Fail the workflow if build
     - name: Early Quit
-      if: steps.build.outcome != 'success'
+      if: ${{ steps.build.outcome != 'success' }}
       run: exit 1
 
     - name: Run Unit Tests
+      id: check
       run: |
         cd guile && \
         make check V=1
@@ -136,8 +144,12 @@ jobs:
         git push origin master
 
     - name: Archive Test Logs
-      if: success() || failure()
       uses: actions/upload-artifact@v4
       with:
         name: Test Logs
         path: ./guile/*.log
+
+    # Fail the workflow if build
+    - name: Late Quit
+      if: ${{ steps.check.outcome != 'success' }}
+      run: exit 1
